# Generated by Django 6.0.3 on 2026-03-23 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("teacher_id", models.CharField(max_length=50, unique=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="observations.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_number", models.PositiveIntegerField(default=1)),
                (
                    "esl_strategy",
                    models.CharField(
                        choices=[
                            ("QS", "QS"),
                            ("TPR", "TPR"),
                            ("VS", "VS"),
                            ("MT", "MT"),
                            ("RP", "RP"),
                            ("DR", "DR"),
                            ("WA", "WA"),
                            ("other", "other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "curriculum",
                    models.CharField(
                        choices=[
                            ("read/lit", "read/lit"),
                            ("math", "math"),
                            ("science", "science"),
                            ("social studies", "social studies"),
                            ("other", "other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "physical_group",
                    models.CharField(
                        choices=[("TC", "TC"), ("SG", "SG"), ("I", "I"), ("P", "P")],
                        max_length=20,
                    ),
                ),
                (
                    "activity_structure",
                    models.CharField(
                        choices=[
                            ("lec/lis", "lec/lis"),
                            ("disc", "disc"),
                            ("coop", "coop"),
                            ("ind", "ind"),
                            ("other", "other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("writing", "writing"),
                            ("reading", "reading"),
                            ("listening", "listening"),
                            ("speaking", "speaking"),
                            ("multi", "multi"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language_content",
                    models.CharField(
                        choices=[
                            ("social", "social"),
                            ("academic", "academic"),
                            ("both", "both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language_instruction_teacher",
                    models.CharField(
                        choices=[
                            ("L1", "L1"),
                            ("L2", "L2"),
                            ("both", "both"),
                            ("neither", "neither"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language_instruction_student",
                    models.CharField(
                        choices=[
                            ("L1", "L1"),
                            ("L2", "L2"),
                            ("both", "both"),
                            ("neither", "neither"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "observer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="observations.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="observations.teacher",
                    ),
                ),
            ],
        ),
    ]
