# Generated by Django 6.0.3 on 2026-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="condition",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="school",
            name="district",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
