# Generated by Django 6.0.4 on 2026-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_school_condition_school_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='activity_structure',
            field=models.CharField(choices=[('lec/lis', 'lec/lis'), ('lec/per', 'lec/per'), ('dir/lis', 'dir/lis'), ('dir/per', 'dir/per'), ('dem/lis', 'dem/lis'), ('led/per', 'led/per'), ('ask/per', 'ask/per'), ('ask/ans', 'ask/ans'), ('ans/ask', 'ans/ask'), ('ev/per', 'ev/per'), ('obs/per', 'obs/per'), ('ev/dis', 'ev/dis'), ('ev/cop', 'ev/cop'), ('obs/dis', 'obs/dis'), ('obs/cop', 'obs/cop'), ('NA/free', 'NA/free'), ('NA/feed', 'NA/feed'), ('NA/tran', 'NA/tran'), ('NA/int', 'NA/int'), ('NA/out', 'NA/out'), ('interac', 'interac')], max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='curriculum',
            field=models.CharField(choices=[('read/lit', 'read/lit'), ('math', 'math'), ('spell', 'spell'), ('hand', 'hand'), ('science', 'science'), ('soc sci', 'soc sci'), ('health', 'health'), ('PE', 'PE'), ('music', 'music'), ('art', 'art'), ('lang', 'lang'), ('compos', 'compos'), ('non-ac', 'non-ac'), ('ESL', 'ESL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='esl_strategy',
            field=models.CharField(choices=[('QS', 'QS'), ('ALS', 'ALS'), ('VS', 'VS'), ('MR', 'MR'), ('AO', 'AO'), ('CG', 'CG'), ('CC', 'CC'), ('LC', 'LC'), ('IT', 'IT'), ('NA', 'NA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='language_content',
            field=models.CharField(choices=[('social', 'social'), ('academic', 'academic'), ('light cog', 'light cog'), ('dns cog', 'dns cog'), ('NA', 'NA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='language_instruction_student',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L1-2', 'L1-2'), ('L2-1', 'L2-1'), ('NA', 'NA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='language_instruction_teacher',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L1-2', 'L1-2'), ('L2-1', 'L2-1'), ('NA', 'NA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='mode',
            field=models.CharField(choices=[('writing', 'writing'), ('reading', 'reading'), ('aural', 'aural'), ('verbal', 'verbal'), ('wr-re', 'wr-re'), ('wr-au', 'wr-au'), ('wr-ver', 'wr-ver'), ('re-wr', 're-wr'), ('re-au', 're-au'), ('re-ver', 're-ver'), ('au-wr', 'au-wr'), ('au-re', 'au-re'), ('ver-wr', 'ver-wr'), ('ver-re', 'ver-re'), ('ver-au', 'ver-au'), ('au-re-ver', 'au-re-ver'), ('NA', 'NA'), ('au-ver', 'au-ver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='physical_group',
            field=models.CharField(choices=[('TC', 'TC'), ('LG', 'LG'), ('SG', 'SG'), ('Pairs', 'Pairs'), ('Single', 'Single')], max_length=20),
        ),
    ]
