# Generated by Django 6.0.4 on 2026-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_observation_activity_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='activity_structure',
            field=models.CharField(choices=[('lec/lis', 'lec/lis'), ('lec/per', 'lec/per'), ('dir/lis', 'dir/lis'), ('dir/per', 'dir/per'), ('dem/lis', 'dem/lis'), ('led/per', 'led/per'), ('ask/per', 'ask/per'), ('ask/ans', 'ask/ans'), ('ans/ask', 'ans/ask'), ('ev/per', 'ev/per'), ('obs/per', 'obs/per'), ('ev/dis', 'ev/dis'), ('ev/cop', 'ev/cop'), ('obs/dis', 'obs/dis'), ('obs/cop', 'obs/cop'), ('NA/free', 'NA/free'), ('NA/feed', 'NA/feed'), ('NA/tran', 'NA/tran'), ('NA/int', 'NA/int'), ('NA/out', 'NA/out'), ('interact', 'interact')], max_length=20),
        ),
    ]
