# Generated by Django 6.0.4 on 2026-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_observation_activity_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='activity_structure',
            field=models.IntegerField(choices=[(1, 'lec/lis'), (2, 'lec/per'), (3, 'dir/lis'), (4, 'dir/per'), (5, 'dem/lis'), (6, 'led/per'), (7, 'ask/per'), (8, 'ask/ans'), (9, 'ans/ask'), (10, 'ev/per'), (11, 'obs/per'), (12, 'ev/dis'), (13, 'ev/cop'), (14, 'obs/dis'), (15, 'obs/cop'), (16, 'NA/free'), (17, 'NA/feed'), (18, 'NA/tran'), (19, 'NA/int'), (20, 'NA/out'), (21, 'interact')]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='curriculum',
            field=models.IntegerField(choices=[(1, 'read/lit'), (2, 'math'), (3, 'spell'), (4, 'hand'), (5, 'science'), (6, 'soc sci'), (7, 'health'), (8, 'PE'), (9, 'music'), (10, 'art'), (11, 'lang'), (12, 'compos'), (13, 'non-ac'), (14, 'ESL')]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='esl_strategy',
            field=models.IntegerField(choices=[(1, 'QS'), (2, 'ALS'), (3, 'VS'), (4, 'MR'), (5, 'AO'), (6, 'CG'), (7, 'CC'), (8, 'LC'), (9, 'IT'), (10, 'NA')]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='language_content',
            field=models.IntegerField(choices=[(1, 'social'), (2, 'academic'), (3, 'light cog'), (4, 'dns cog'), (5, 'NA')]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='language_instruction_student',
            field=models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L1-2'), (4, 'L2-1'), (5, 'NA')]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='language_instruction_teacher',
            field=models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L1-2'), (4, 'L2-1'), (5, 'NA')]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='mode',
            field=models.IntegerField(choices=[(1, 'writing'), (2, 'reading'), (3, 'aural'), (4, 'verbal'), (5, 'wr-re'), (6, 'wr-au'), (7, 'wr-ver'), (8, 're-wr'), (9, 're-au'), (10, 're-ver'), (11, 'au-wr'), (12, 'au-re'), (13, 'ver-wr'), (14, 'ver-re'), (15, 'ver-au'), (16, 'au-re-ver'), (17, 'NA'), (18, 'au-ver')]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='physical_group',
            field=models.IntegerField(choices=[(1, 'TC'), (2, 'LG'), (3, 'SG'), (4, 'Pairs'), (5, 'Single')]),
        ),
    ]
