# Generated by Django 6.0.4 on 2026-04-22 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_observationsession_observation_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.observationsession'),
        ),
    ]
