# Generated by Django 6.0.3 on 2026-04-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0003_update_choices"),
        ("observations", "0007_alter_observation_session"),
    ]

    operations = []
